### ISSUE TITLE
`wrong number of arguments (given 1, expected 0)`

### ISSUE THREAD

**Issue by grzegorzglikwitkowski** [doriantaylor/rb-uuid-ncname#1]
Instead of 

https://github.com/doriantaylor/rb-uuid-ncname/blob/8058a3136a646fef4586b95b3e4373e826b34277/lib/uuid/ncname.rb#L101

shouldn't there be
` raise 'Radix must be either 32 or 64' unless [32, 64].include? radix`

**Comment by doriantaylor** [comment]
I suppose it should, but that's weird. I can't replicate. What version of Ruby/what context are you running this in?

**Comment by grzegorzglikwitkowski** [comment]
Hi, sorry for late answer, I was on an annual leave :).

ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

I am just calling:

uu = UUIDTools::UUID.random_create
id = to_ncname uu

BTW. Nice work on your gem :)

**Comment by doriantaylor** [comment]
Thanks!
